// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5PKNmo6dM12loLIddKt9sHc4MUi_BrVY',
    appId: '1:938301353067:web:313d126bf753905006952e',
    messagingSenderId: '938301353067',
    projectId: 'web-test-c4224',
    authDomain: 'web-test-c4224.firebaseapp.com',
    databaseURL: 'https://web-test-c4224-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'web-test-c4224.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoSysSGrrzDCV8Q0qCLDNoRxyWMSs-OhQ',
    appId: '1:938301353067:android:82481d637698d99206952e',
    messagingSenderId: '938301353067',
    projectId: 'web-test-c4224',
    databaseURL: 'https://web-test-c4224-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'web-test-c4224.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtZL3lb2qTlKMUGlNITlva-Uyyc_F9XAw',
    appId: '1:938301353067:ios:001acf79b3311ca206952e',
    messagingSenderId: '938301353067',
    projectId: 'web-test-c4224',
    databaseURL: 'https://web-test-c4224-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'web-test-c4224.appspot.com',
    iosBundleId: 'com.example.webApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtZL3lb2qTlKMUGlNITlva-Uyyc_F9XAw',
    appId: '1:938301353067:ios:850cd9898c1a040e06952e',
    messagingSenderId: '938301353067',
    projectId: 'web-test-c4224',
    databaseURL: 'https://web-test-c4224-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'web-test-c4224.appspot.com',
    iosBundleId: 'com.example.webApp.RunnerTests',
  );
}
